# Example xproc configuration file

show_timestamp = true

[[processes]]
name = "npm"
command = "node"
args = ["./test_helpers/process.js"]
prefix = "FRONT"
color = "green"
on_failure = "wait"
on_complete =  "wait"
  [processes.trigger]
    restart_process = true
    [processes.trigger.filesystem]
      # debounce_ms = 50
      watch = [".", "./tests/.tmp"]
      ignore = ["test"]
      filter_for = ["*.test"]
    [processes.trigger.process]


[[processes]]
name = "example fail"
command = "go"
show_pid = false
args = ["run", "main.go"]
prefix = "BACK"
color = "blue"
on_failure = "restart"
on_complete = "restart"
restart_attempts = 3
silent = false

[[processes]]
name = "example fail2"
command = "go"
show_pid = false
args = ["run", "main.go"]
prefix = "TRIG"
color = "yellow"
on_failure = "wait"
on_complete = "wait"
restart_attempts = 0
silent = false

