# Example xproc configuration file

[[processes]]
name = "echo"
command = "echo hjello"
prefix = "FRONT"
color = "green"
on_failure = "buzzkill"
on_complete = "wait"

[[processes]]
name = "example fail"
command = "go"
args = ["run", "main.go"]
prefix = "BACK"
color = "blue"
on_failure = "buzzkill"