# Example xproc configuration file

show_timestamp = true
indicate_every_line=true

[[processes]]
name = "cmd"
command = "cmd"
prefix = "FRONT"
color = "green"
on_failure = "buzzkill"
on_complete = "wait"
stdin_on_start = "echo helo >> hello.txt"



[[processes]]
name = "example fail"
command = "go"
show_pid = false
args = ["run", "main.go"]
prefix = "BACK"
color = "blue"
on_failure = "wait"

# [[processes]]
# name = "example fail2"
# command = "go"
# args = ["run", "main.go"]
# prefix = "BACK2"
# color = "red"
# on_failure = "buzzkill"

# [[processes]]
# name = "echo"
# command = "echo hjello"
# prefix = "FRONT"
# color = "green"
# on_failure = "buzzkill"
# on_complete = "wait"
